### ISSUE TITLE
On the scope of this package

### ISSUE THREAD

**Issue by JMmontilla** [JuliaGeometry/Meshing.jl#22]
Hello I´m trying to mesh a 3d object that I have as a triangulated surface (each face is given by 3 points), here is an example of how it looks like:

![eros](https://user-images.githubusercontent.com/38725172/59265945-bee83880-8c46-11e9-834f-47b2db8dafae.png)

I want to get a 3d mesh with tetrahedron of the whole volume to model the internal mass distribution. I thought that maybe this package would do the trick, but reading carefully the documentation provided I currently understand that this is only possible if you have an implicit function of the surface that encloses the 3d body (using the `SignedDistanceField` function). Am I wrong in this supposition or there is more functionality to Meshing.jl?

**Comment by sjkelly** [comment]
This library currently only supports surface Meshes (triangles and quads). You are correct that the library supports only data from a SignedDistanceField at present. I have some work towards alternative meshing algorithms that require the underlying function to be present so in the near future there will be an alternative API for implicit functions that will allow for more direct meshing approaches.

For Tetrahedral meshes there is some preliminary work for wrapping [tetgen](https://github.com/JuliaGeometry/TetGen.jl) and [Gmsh](https://github.com/JuliaFEM/Gmsh.jl). I do want to support tetrahedral meshing in the future. It is possible I may have some work towards this in a few months as I am working with a researcher who is well-versed in this area.
