### ISSUE TITLE
Axis Arrays and NRRD

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/Meshing.jl#31]
The NRRD format is commonly used for dicom data exports. The NRRD FileIO loader produces an axis array, which is similar to the SDF format, but significantly more mature and feature-rich. In order to be useful for the julia medical/imaging communities, it might be good to have support for Axis Arrays to make the pipeline to a mesh far simpler.

**Comment by SimonDanisch** [comment]
cc @Kevin-Mattheus-Moerman

**Comment by sjkelly** [comment]
`isosurface` and `AbstractMesh` calls will now handle AbstractArray so `HomogenousMesh(load("my.nrrd"), MarchingCubes())` will just work. See: https://juliageometry.github.io/Meshing.jl/dev/examples/#NRRD-Data-1
