### ISSUE TITLE
What is in the name?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaGeometry/Meshing.jl#50]
I like what the package does, I really do. The name, however, promises too much. "Meshing" seems to say "I do meshing". This implies not only producing meshes in different dimensions (boundary and interior of domains), but also  producing meshes with some guarantees on shape (in some measure: aspect ratios, dihedral angles, ...).

Perhaps this is coming, but if not, then the name is slightly misleading.

**Comment by sjkelly** [comment]
You are right. It probably should be "SurfaceMeshing.jl" or "Isosurface.jl" given the current scope. 4 (!) years ago when we broke this out of Meshes.jl we were only really concerned about surfaces, and higher order things weren't really on our minds. Meshing.jl seemed appropriate. Issues like #22 illustrate the ambiguity "Meshing" to users.

I am working on refinement strategies for surface and tetrahedral meshes in another repo. It seems reasonable that they would live here, but I need to develop different approaches to avoid up-licensing to GPL.
