### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by markmbaum** [JuliaGeometry/Meshing.jl#74]
Does this package have documentation? Where can I find it?

**Comment by SimonDanisch** [comment]
![image](https://user-images.githubusercontent.com/1010467/81955054-e9d2cd80-9609-11ea-9595-2939e461b38f.png)
https://juliageometry.github.io/Meshing.jl/stable/

**Comment by sjkelly** [comment]
[JuliaHub](https://juliahub.com) is a really good resource for doc search across the ecosystem as well.
e.g:
https://juliahub.com/ui/Documentation?q=isosurface
